/*
 * Generated by XDoclet - Do not edit!
 */
package foo.bar.services;

/**
 * Remote interface for HelloService.
 * @generated 
 * @wtp generated
 */
public interface HelloService
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String sayHello( java.lang.String name )
      throws java.rmi.RemoteException;

}
