/*
 * Generated by XDoclet - Do not edit!
 */
package foo.bar.services;

/**
 * Local interface for HelloService.
 * @generated 
 * @wtp generated
 */
public interface HelloServiceLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String sayHello( java.lang.String name ) ;

}
