/*
 * Generated by XDoclet - Do not edit!
 */
package foo.bar.services;

/**
 * Session layer for HelloService.
 * 
 * @generated
 * @wtp generated
 */
public class HelloServiceSession extends foo.bar.services.HelloServiceBean
		implements javax.ejb.SessionBean {
	private static final long serialVersionUID = 2805170292740885065L;

	public void ejbActivate() throws javax.ejb.EJBException,
			java.rmi.RemoteException {

		super.ejbActivate();
	}

	public void ejbPassivate() throws javax.ejb.EJBException,
			java.rmi.RemoteException {
		super.ejbPassivate();
	}

	public void setSessionContext(javax.ejb.SessionContext ctx)
			throws javax.ejb.EJBException, java.rmi.RemoteException {
		super.setSessionContext(ctx);
	}

	public void unsetSessionContext() {
	}

	public void ejbRemove() throws javax.ejb.EJBException,
			java.rmi.RemoteException {
		super.ejbRemove();
	}

}
