/*
 * Generated by XDoclet - Do not edit!
 */
package foo.bar.services;

/**
 * Local home interface for HelloService.
 * @generated 
 * @wtp generated
 */
public interface HelloServiceLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HelloServiceLocal";
   public static final String JNDI_NAME="HelloServiceLocal";

   public foo.bar.services.HelloServiceLocal create()
      throws javax.ejb.CreateException;

}
